export const VIEWPORT = Object.freeze({ width: 960, height: 540, floorY: 451 });

export const ROUND = Object.freeze({
  seconds: 60,
  winsRequired: 2,
  introSeconds: 2.35,
  outroSeconds: 2.6,
});

export const STAGES = Object.freeze({
  moonTemple: Object.freeze({
    id: "moonTemple",
    name: "SHATTERED MOON TEMPLE",
    image: "assets/arena-moon-temple.png",
    fog: "91, 98, 100",
    moteBright: "#f69b3a",
    moteDim: "#b5a78e",
  }),
  infernalForge: Object.freeze({
    id: "infernalForge",
    name: "THE INFERNAL FORGE",
    image: "assets/arena-infernal-forge.png",
    fog: "127, 40, 18",
    moteBright: "#ff9a32",
    moteDim: "#c4451f",
  }),
  moonGate: Object.freeze({
    id: "moonGate",
    name: "MOON GATE MONASTERY",
    image: "assets/arena-moon-gate.png",
    fog: "111, 132, 153",
    moteBright: "#eacb76",
    moteDim: "#a7b7c6",
  }),
  venomMarsh: Object.freeze({
    id: "venomMarsh",
    name: "THE VENOM MARSH",
    image: "assets/arena-venom-marsh.png",
    fog: "70, 112, 67",
    moteBright: "#9fdb65",
    moteDim: "#809b62",
  }),
});

export const CHARACTERS = Object.freeze({
  riven: Object.freeze({
    id: "riven",
    name: "RIVEN",
    epithet: "THE EXILED GUARDIAN",
    sprite: "assets/riven-sprites.png",
    speed: 238,
    jump: 610,
    power: 1.08,
    scale: 1,
    accent: "#d4371f",
    finisher: "SOULFALL",
    finisherStyle: "soul",
  }),
  veyra: Object.freeze({
    id: "veyra",
    name: "VEYRA",
    epithet: "THE STORM CHAMPION",
    sprite: "assets/veyra-sprites.png",
    speed: 265,
    jump: 655,
    power: 0.96,
    scale: 0.98,
    accent: "#43a5a5",
    finisher: "TEMPEST CROWN",
    finisherStyle: "tempest",
  }),
  kael: Object.freeze({
    id: "kael",
    name: "KAEL",
    epithet: "THE ASH-BOUND HUNTER",
    sprite: "assets/kael-sprites-v3.png",
    speed: 248,
    jump: 625,
    power: 1.05,
    scale: 1,
    accent: "#ef5a24",
    finisher: "ASHEN VERDICT",
    finisherStyle: "ember",
  }),
  neris: Object.freeze({
    id: "neris",
    name: "NERIS",
    epithet: "THE FROSTBOUND NOMAD",
    sprite: "assets/neris-sprites-v3.png",
    speed: 254,
    jump: 640,
    power: 0.99,
    scale: 0.98,
    accent: "#93dfff",
    finisher: "WHITE SILENCE",
    finisherStyle: "frost",
  }),
  vance: Object.freeze({
    id: "vance",
    name: "VANCE",
    epithet: "THE GILDED CHAMPION",
    sprite: "assets/vance-sprites.png",
    speed: 271,
    jump: 648,
    power: 0.95,
    scale: 1,
    accent: "#d84d70",
    finisher: "FINAL CURTAIN",
    finisherStyle: "flash",
  }),
  orun: Object.freeze({
    id: "orun",
    name: "ORUN",
    epithet: "THE STORM ORACLE",
    sprite: "assets/orun-sprites-v2.png",
    speed: 225,
    jump: 600,
    power: 1.12,
    scale: 1.02,
    accent: "#829dff",
    finisher: "HEAVEN'S BREAK",
    finisherStyle: "thunder",
  }),
  serika: Object.freeze({
    id: "serika",
    name: "SERIKA",
    epithet: "THE BLOOD-MOON FANG",
    sprite: "assets/serika-sprites-v2.png",
    speed: 279,
    jump: 672,
    power: 0.93,
    scale: 0.98,
    accent: "#a64dff",
    finisher: "VIOLET MAW",
    finisherStyle: "fang",
  }),
  ilyra: Object.freeze({
    id: "ilyra",
    name: "ILYRA",
    epithet: "THE FALLEN SKY HEIR",
    sprite: "assets/ilyra-sprites.png",
    speed: 262,
    jump: 660,
    power: 0.98,
    scale: 0.98,
    accent: "#8198f2",
    finisher: "LAST BREATH",
    finisherStyle: "sky",
  }),
  dravok: Object.freeze({
    id: "dravok",
    name: "DRAVOK",
    epithet: "THE DETHRONED TYRANT",
    sprite: "assets/dravok-sprites.png",
    speed: 205,
    jump: 570,
    power: 1.18,
    scale: 1.05,
    accent: "#b92b1e",
    finisher: "TYRANT'S ECLIPSE",
    finisherStyle: "quake",
  }),
  sythra: Object.freeze({
    id: "sythra",
    name: "SYTHRA",
    epithet: "THE VENOM MARSH HUNTER",
    sprite: "assets/sythra-sprites.png",
    speed: 286,
    jump: 680,
    power: 0.92,
    scale: 0.99,
    accent: "#7dbb3d",
    finisher: "VENOM BLOOM",
    finisherStyle: "venom",
  }),
  gorrak: Object.freeze({
    id: "gorrak",
    name: "GORRAK",
    epithet: "THE ASH-WASTE HUNTER",
    sprite: "assets/gorrak-sprites.png",
    speed: 242,
    jump: 612,
    power: 1.1,
    scale: 1.02,
    accent: "#d06d3b",
    finisher: "OBSIDIAN SHEAR",
    finisherStyle: "spurs",
  }),
  mara: Object.freeze({
    id: "mara",
    name: "MARA VOSS",
    epithet: "THE FRONTIER COMMANDO",
    sprite: "assets/mara-sprites.png",
    speed: 276,
    jump: 668,
    power: 0.94,
    scale: 0.98,
    accent: "#e47b32",
    finisher: "BREACH PROTOCOL",
    finisherStyle: "barrage",
  }),
});

export const ATTACKS = Object.freeze({
  highPunch: Object.freeze({
    frame: 3,
    damage: 8,
    reach: 111,
    windup: 0.07,
    active: 0.11,
    duration: 0.32,
    hitstun: 0.2,
    knockback: 22,
    height: "high",
    sound: "punch",
  }),
  lowPunch: Object.freeze({
    frame: 3,
    damage: 6,
    reach: 93,
    windup: 0.045,
    active: 0.1,
    duration: 0.25,
    hitstun: 0.15,
    knockback: 13,
    height: "mid",
    sound: "punch",
  }),
  highKick: Object.freeze({
    frame: 4,
    damage: 13,
    reach: 145,
    windup: 0.15,
    active: 0.13,
    duration: 0.51,
    hitstun: 0.31,
    knockback: 39,
    height: "high",
    sound: "kick",
  }),
  lowKick: Object.freeze({
    frame: 4,
    damage: 10,
    reach: 122,
    windup: 0.1,
    active: 0.14,
    duration: 0.42,
    hitstun: 0.25,
    knockback: 31,
    height: "low",
    sound: "kick",
  }),
});

export const KEYBOARD_MAP = Object.freeze([
  Object.freeze({
    left: "KeyA",
    right: "KeyD",
    up: "KeyW",
    down: "KeyS",
    highPunch: "KeyF",
    lowPunch: "KeyV",
    block: "KeyG",
    highKick: "KeyH",
    lowKick: "KeyN",
  }),
  Object.freeze({
    left: "ArrowLeft",
    right: "ArrowRight",
    up: "ArrowUp",
    down: "ArrowDown",
    highPunch: "KeyJ",
    lowPunch: "KeyM",
    block: "KeyK",
    highKick: "KeyL",
    lowKick: "Period",
  }),
]);

export const ACTIONS = Object.freeze([
  "left",
  "right",
  "up",
  "down",
  "highPunch",
  "lowPunch",
  "block",
  "highKick",
  "lowKick",
]);
